//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeedAngel.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dispensary
    {
        public Dispensary()
        {
            this.Pictures = new HashSet<Picture>();
            this.Videos = new HashSet<Video>();
        }
    
        public int DispensaryId { get; set; }
        public string DispensaryName { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zipcode { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> TimeZoneId { get; set; }
        public string PhoneNo { get; set; }
        public string Website { get; set; }
        public string Email { get; set; }
        public string AvatarName { get; set; }
        public string AvatarPath { get; set; }
        public string Facebook { get; set; }
        public string Twitter { get; set; }
        public string Instagram { get; set; }
        public string IntroBody { get; set; }
        public string Body { get; set; }
        public Nullable<bool> IsHandicap { get; set; }
        public Nullable<bool> IsSecurityGuard { get; set; }
        public Nullable<bool> IsLounge { get; set; }
        public Nullable<bool> IsCreditCards { get; set; }
        public Nullable<bool> Is18 { get; set; }
        public Nullable<bool> Is21 { get; set; }
        public Nullable<bool> IsPictures { get; set; }
        public Nullable<bool> IsVideos { get; set; }
        public string Country { get; set; }
        public string SunDayOpen { get; set; }
        public string SunDayClose { get; set; }
        public string MonDayOpen { get; set; }
        public string MonDayClose { get; set; }
        public string TuesDayOpen { get; set; }
        public string TuesDayClose { get; set; }
        public string WednesDayOpen { get; set; }
        public string WednesDayClose { get; set; }
        public string ThursDayOpen { get; set; }
        public string ThursDayClose { get; set; }
        public string FriDayOpen { get; set; }
        public string FriDayClose { get; set; }
        public string SaturDayOpen { get; set; }
        public string SaturDayClose { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Picture> Pictures { get; set; }
        public virtual ICollection<Video> Videos { get; set; }
    }
}
