//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeedAngel.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public int DoctorId { get; set; }
        public string DoctorName { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zipcode { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> TimeZoneId { get; set; }
        public string PhoneNo { get; set; }
        public string Website { get; set; }
        public string Email { get; set; }
        public string AvatarName { get; set; }
        public string AvatarPath { get; set; }
        public string Country { get; set; }
        public Nullable<bool> IsHandicap { get; set; }
        public Nullable<bool> IsSecurityGuard { get; set; }
        public Nullable<bool> IsCreditCards { get; set; }
        public Nullable<bool> Is18 { get; set; }
        public Nullable<bool> Is21 { get; set; }
        public string IntroBody { get; set; }
        public string Body { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
