//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeedAngel.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Dispensaries = new HashSet<Dispensary>();
            this.Doctors = new HashSet<Doctor>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string ActivationCode { get; set; }
        public Nullable<System.DateTime> RequestedActivationDate { get; set; }
        public string ProfileImageName { get; set; }
        public string ProfileImagePath { get; set; }
        public string State { get; set; }
        public string Zipcode { get; set; }
        public Nullable<int> RegionId { get; set; }
        public string Facebook { get; set; }
        public string Twitter { get; set; }
        public string Instagram { get; set; }
        public string Gender { get; set; }
        public string MaritalStatus { get; set; }
        public string Status { get; set; }
        public string FavWayToGetHigh { get; set; }
        public string FavDispensory { get; set; }
        public string FavStrains { get; set; }
        public string AboutMe { get; set; }
        public string TellForGetHigh { get; set; }
    
        public virtual ICollection<Dispensary> Dispensaries { get; set; }
        public virtual ICollection<Doctor> Doctors { get; set; }
    }
}
